Update AWS SDK to support M7g* EC2 instances
jenkinsci/ec2-plugin pull request #840
Opened 2023-04-13 03:40 UTC by silverjam

Jira: https://issues.jenkins.io/browse/JENKINS-71059

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-04-13 07:17 UTC, mawinter69 requested changes
You're changing the dependency from a jenkins plugin to a plain java library. That way you will package those jars directly in this plugin. There are other plugins that need those libraries as well and by wrapping them in a plugin you can ensure that you have only a single version of those libraries in Jenkins and not 5 different version in each plugin that needs it.
So you need to change the jenkins plugins that wrap the corresponding aws libraries and not the consumers like the ec2 plugin
That will most likely also fix the build issues

2023-04-13 09:21 UTC, silverjam commented
Alright, I think that means I'm waiting on https://github.com/jenkinsci/aws-java-sdk-plugin/pull/975

2023-04-15 04:09 UTC, silverjam commented
Ping @mawinter69 @Vlatombe -- I think this is ready for review.  Thank you!

2023-04-15 07:25 UTC, Vlatombe commented
Updating the aws java sdk dependency is not needed, unless the plugin needs to use a new API. Just upgrade the sdk plugin and you'll be able to use the new instance type.

2023-04-15 16:36 UTC, silverjam commented
Ok, will give it a shot!

2023-05-07 00:35 UTC, closed without merging